export const PERMISSIONS = [
  'user.read',
  'user.create',
  'user.update',
  'user.delete',
  'role.manage',
  'customer.read',
  'customer.create',
  'customer.update',
  'customer.delete',
  'product.read',
  'product.create',
  'product.update',
  'product.delete',
  'category.read',
  'category.create',
  'category.update',
  'category.delete',
  'order.read',
  'order.create',
  'order.update',
  'order.cancel',
  'review.read',
  'review.moderate',
  'inventory.read',
  'inventory.update',
  'supplier.read',
  'supplier.manage',
  'purchase_order.read',
  'purchase_order.manage',
  'promotion.read',
  'promotion.manage',
  'loyalty.read',
  'loyalty.manage',
  'notification.read',
  'notification.manage',
  'email_template.read',
  'email_template.manage',
  'custom_cake.read',
  'custom_cake.manage',
  'report.read',
  'settings.read',
  'settings.update',
  'settings.security',
  'audit.read'
] as const

export type PermissionKey = (typeof PERMISSIONS)[number]

export const PERMISSION_DESCRIPTIONS: Record<PermissionKey, string> = {
  'user.read': 'View staff and customer accounts',
  'user.create': 'Create accounts',
  'user.update': 'Update accounts',
  'user.delete': 'Disable accounts',
  'role.manage': 'Change role permissions',
  'customer.read': 'View customers',
  'customer.create': 'Create customers',
  'customer.update': 'Update customers',
  'customer.delete': 'Archive customers',
  'product.read': 'View products',
  'product.create': 'Create products',
  'product.update': 'Update products',
  'product.delete': 'Archive products',
  'category.read': 'View categories',
  'category.create': 'Create categories',
  'category.update': 'Update categories',
  'category.delete': 'Archive categories',
  'order.read': 'View orders',
  'order.create': 'Create orders',
  'order.update': 'Update orders',
  'order.cancel': 'Cancel orders',
  'review.read': 'View reviews',
  'review.moderate': 'Moderate reviews',
  'inventory.read': 'View inventory',
  'inventory.update': 'Adjust inventory',
  'supplier.read': 'View suppliers',
  'supplier.manage': 'Manage suppliers',
  'purchase_order.read': 'View purchase orders',
  'purchase_order.manage': 'Manage purchase orders',
  'promotion.read': 'View promotions',
  'promotion.manage': 'Manage promotions and coupons',
  'loyalty.read': 'View loyalty balances',
  'loyalty.manage': 'Adjust loyalty points',
  'notification.read': 'View notifications',
  'notification.manage': 'Manage notifications',
  'email_template.read': 'View email templates',
  'email_template.manage': 'Edit email templates',
  'custom_cake.read': 'View custom cake requests',
  'custom_cake.manage': 'Manage custom cake requests',
  'report.read': 'View reports',
  'settings.read': 'View settings',
  'settings.update': 'Update store settings',
  'settings.security': 'Update security and OTP settings',
  'audit.read': 'View audit logs'
}

export const SECURITY_SETTING_GROUPS = ['SECURITY', 'OTP'] as const
